{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "source-pg.fullname" . }}
  labels:
    {{- include "source-pg.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.auth.password | quote }}
  replication-password: {{ .Values.auth.replicationPassword | quote }}
{{- end }}
