#!/usr/bin/env bash
# Boots the real postgres image against the chart's *rendered* ConfigMaps under
# plain docker, and runs the same acceptance check as `make verify`. Useful when
# you have no cluster handy, and as a fast pre-flight before installing.
set -euo pipefail

CHART=${CHART:-charts/pit}
CONTAINER=${CONTAINER:-pit-source-pg-verify}
PGUSER=${PGUSER:-pit}
PGDATABASE=${PGDATABASE:-pit}
PGPASSWORD_=${PGPASSWORD_:-verify-password}
REPL_USER=${REPL_USER:-debezium}
REPL_PASSWORD=${REPL_PASSWORD:-verify-replication-password}

command -v helm >/dev/null || { echo "helm is required (brew install helm)"; exit 1; }
command -v docker >/dev/null || { echo "docker is required"; exit 1; }

TMP=$(mktemp -d)
cleanup() {
  docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
  rm -rf "$TMP"
}
trap cleanup EXIT

# --- render ---------------------------------------------------------------
# The ConfigMaps are generated by our own templates, so their shape is known:
# one `  <key>: |` line followed by a 4-space-indented block.
extract_block() {
  awk -v key="$1" '
    index($0, "  " key ": |") == 1 { inblock = 1; next }
    inblock {
      if ($0 ~ /^    /) { print substr($0, 5); next }
      if ($0 ~ /^[[:space:]]*$/) { print ""; next }
      inblock = 0
    }
  '
}
block_keys() {
  awk '/^  [A-Za-z0-9._-]+: \|/ { sub(/: \|.*/, ""); sub(/^  /, ""); print }'
}

render() { helm template verify "$CHART" --show-only "charts/source-pg/templates/$1"; }

CONF_YAML=$(render configmap-postgresql-conf.yaml)
INITDB_YAML=$(render configmap-initdb.yaml)
STS_YAML=$(render statefulset.yaml)

IMAGE=$(printf '%s\n' "$STS_YAML" \
  | grep -m1 -E '^[[:space:]]+image:' \
  | sed -E 's/.*image:[[:space:]]*"?([^"[:space:]]+)"?.*/\1/')
[[ -n $IMAGE ]] || { echo "could not determine image from rendered StatefulSet"; exit 1; }

mkdir -p "$TMP/conf" "$TMP/initdb"
printf '%s\n' "$CONF_YAML" | extract_block "postgresql.conf" > "$TMP/conf/postgresql.conf"
[[ -s $TMP/conf/postgresql.conf ]] || { echo "rendered postgresql.conf is empty"; exit 1; }

while read -r key; do
  [[ -n $key ]] || continue
  printf '%s\n' "$INITDB_YAML" | extract_block "$key" > "$TMP/initdb/$key"
  chmod 0755 "$TMP/initdb/$key"
done < <(printf '%s\n' "$INITDB_YAML" | block_keys)

echo "==> image: $IMAGE"
echo "==> rendered postgresql.conf:"
sed 's/^/    /' "$TMP/conf/postgresql.conf"
echo "==> init scripts: $(ls -1 "$TMP/initdb" | tr '\n' ' ')"

# --- boot -----------------------------------------------------------------
docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
docker run -d --name "$CONTAINER" \
  -e POSTGRES_DB="$PGDATABASE" \
  -e POSTGRES_USER="$PGUSER" \
  -e POSTGRES_PASSWORD="$PGPASSWORD_" \
  -e PIT_REPLICATION_USER="$REPL_USER" \
  -e PIT_REPLICATION_PASSWORD="$REPL_PASSWORD" \
  -e PGDATA=/var/lib/postgresql/data/pgdata \
  -v "$TMP/conf":/etc/postgresql:ro \
  -v "$TMP/initdb":/docker-entrypoint-initdb.d:ro \
  "$IMAGE" -c config_file=/etc/postgresql/postgresql.conf >/dev/null

echo "==> waiting for readiness"
for _ in $(seq 1 60); do
  if docker exec "$CONTAINER" pg_isready -h 127.0.0.1 -U "$PGUSER" -d "$PGDATABASE" >/dev/null 2>&1; then
    ready=1; break
  fi
  sleep 1
done
if [[ ${ready:-0} -ne 1 ]]; then
  echo "FAIL: postgres never became ready"
  docker logs "$CONTAINER" 2>&1 | tail -40
  exit 1
fi

q() { docker exec "$CONTAINER" psql -U "$PGUSER" -d "$PGDATABASE" -Atc "$1"; }

# --- assert ---------------------------------------------------------------
docker exec "$CONTAINER" psql -U "$PGUSER" -d "$PGDATABASE" -c \
  "select name, setting from pg_settings
   where name in ('wal_level','max_replication_slots','max_wal_senders','wal_keep_size');"

level=$(q 'show wal_level;' | tr -d '\r')
if [[ $level != logical ]]; then
  echo "FAIL: wal_level is '$level', expected 'logical'"
  exit 1
fi

# The setting being right is not the same as decoding working. Open a real slot.
q "select pg_create_logical_replication_slot('pit_verify','pgoutput');" >/dev/null
q "select pg_drop_replication_slot('pit_verify');" >/dev/null

repl=$(q "select rolreplication from pg_roles where rolname = '$REPL_USER';" | tr -d '\r')
if [[ $repl != t ]]; then
  echo "FAIL: role '$REPL_USER' missing or lacks REPLICATION (rolreplication=$repl)"
  exit 1
fi

echo "PASS: wal_level=logical, logical slot creation works, '$REPL_USER' has REPLICATION"
