apiVersion: v1
kind: Service
metadata:
  name: {{ include "connect.fullname" . }}
  labels:
    {{- include "connect.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: rest
      port: {{ .Values.service.port }}
      targetPort: rest
      protocol: TCP
  selector:
    {{- include "connect.selectorLabels" . | nindent 4 }}
